### ISSUE TITLE
Oscillator.h librairie problem

### ISSUE THREAD

**Issue by ttpvanier** [OttoDIY/Libraries#5]
Bonjour! When I try to run some sketchbooks in Arduino IDE, I have this error message : "Oscillator.h : no such file or directory." The other librairies are ok. Thank you!

**Comment by cparrapa** [comment]
strange is right here https://github.com/OttoDIY/Libraries/blob/master/Oscillator/Oscillator.h

**Comment by ttpvanier** [comment]
Hi! There was no text file with the library. We have created one and everything is now ok! Thank you! Otto is now very happy! ;-)

**Comment by cparrapa** [comment]
Hi @ttpvanier 
what text file? can you do a pull request to see please?

**Comment by ttpvanier** [comment]
Hi! There is no Library properties file for Oscillator.h and Oscillator.cpp in the ZIP folder this is why I was not able to install it.

![image](https://user-images.githubusercontent.com/60986174/75564125-8cbb7880-5a19-11ea-9d89-7a61d04c8edb.png)

**Comment by cparrapa** [comment]
Strange i still not see why is needed there, maybe is because installing via zip requires? when unzip on folder works normally

**Comment by ttpvanier** [comment]
Yes, Installing via zip requires the Library properties. I use Arduino
create online with my students and the libraries must be in ZIP format in
order to be imported.

Here, my two zip folders in which I added the library properties.
English is not my first language, maybe my message was not clear enough at
the beginning. ;-)

**Comment by cparrapa** [comment]
Thanks
Where are the files can you do a pull request maybe?

**Comment by ttpvanier** [comment]
What is that? (pull request?). My files are in my previous post.

**Comment by cparrapa** [comment]
i try to look for them but do not see, they do not seem attached here in github, is it only one txt file you can just copy and paste here and i do the rest 

Thanks
