### ISSUE TITLE
error compiling

### ISSUE THREAD

**Issue by indrawanfian** [OttoDIY/Libraries#6]
sorry i'm beginner and i want to build ottoDIY, but i just get error compiling just shown on the picture. even though I already entered the otto libraries file into the arduino libraries
![Capture_](https://user-images.githubusercontent.com/48905011/77500417-889f4100-6e87-11ea-81bd-c8cab04ca083.PNG)

**Comment by cparrapa** [comment]
@indrawanfian
if you are a beginner better just use Otto Blockly directly https://www.ottodiy.com/#blockly no need to worry about libraries that seems you have not installed.

Once you fill confident follow the process well to install Arduino libraries, https://www.arduino.cc/en/Guide/Libraries

Also detailed in full documentation of Otto
https://wikifactory.com/+OttoDIY/otto-diy
